<?php

namespace ContainerIub22nN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Usrp9xwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Usrp9xw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Usrp9xw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'sociosRepository' => ['privates', 'App\\Repository\\SociosRepository', 'getSociosRepositoryService', true],
        ], [
            'paginator' => '?',
            'sociosRepository' => 'App\\Repository\\SociosRepository',
        ]);
    }
}
