<?php

namespace ContainerIub22nN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AGpzxP7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aGpzxP7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aGpzxP7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'empresaRepository' => ['privates', 'App\\Repository\\EmpresaRepository', 'getEmpresaRepositoryService', true],
            'sociosRepository' => ['privates', 'App\\Repository\\SociosRepository', 'getSociosRepositoryService', true],
        ], [
            'empresaRepository' => 'App\\Repository\\EmpresaRepository',
            'sociosRepository' => 'App\\Repository\\SociosRepository',
        ]);
    }
}
