<?php

namespace ContainerIub22nN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q1uksm9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q1uksm9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q1uksm9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ApiGeradorPDFController::generatePdf' => ['privates', '.service_locator.aGpzxP7', 'get_ServiceLocator_AGpzxP7Service', true],
            'App\\Controller\\CadastraEmpresaController::adicionar' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\CadastraEmpresaController::editar' => ['privates', '.service_locator.Nl_ldhT', 'get_ServiceLocator_NlLdhTService', true],
            'App\\Controller\\CadastraEmpresaController::excluir' => ['privates', '.service_locator.Nl_ldhT', 'get_ServiceLocator_NlLdhTService', true],
            'App\\Controller\\CadastraEmpresaController::index' => ['privates', '.service_locator.7zSLLSc', 'get_ServiceLocator_7zSLLScService', true],
            'App\\Controller\\CadastroSocioController::adicionar' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\CadastroSocioController::editar' => ['privates', '.service_locator.pRI1W04', 'get_ServiceLocator_PRI1W04Service', true],
            'App\\Controller\\CadastroSocioController::excluir' => ['privates', '.service_locator.pRI1W04', 'get_ServiceLocator_PRI1W04Service', true],
            'App\\Controller\\CadastroSocioController::index' => ['privates', '.service_locator.Usrp9xw', 'get_ServiceLocator_Usrp9xwService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.8HRVZ6e', 'get_ServiceLocator_8HRVZ6eService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.V6D1oJY', 'get_ServiceLocator_V6D1oJYService', true],
            'App\\Controller\\VerEmpresaSociosController::index' => ['privates', '.service_locator.7zSLLSc', 'get_ServiceLocator_7zSLLScService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ApiGeradorPDFController:generatePdf' => ['privates', '.service_locator.aGpzxP7', 'get_ServiceLocator_AGpzxP7Service', true],
            'App\\Controller\\CadastraEmpresaController:adicionar' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\CadastraEmpresaController:editar' => ['privates', '.service_locator.Nl_ldhT', 'get_ServiceLocator_NlLdhTService', true],
            'App\\Controller\\CadastraEmpresaController:excluir' => ['privates', '.service_locator.Nl_ldhT', 'get_ServiceLocator_NlLdhTService', true],
            'App\\Controller\\CadastraEmpresaController:index' => ['privates', '.service_locator.7zSLLSc', 'get_ServiceLocator_7zSLLScService', true],
            'App\\Controller\\CadastroSocioController:adicionar' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\CadastroSocioController:editar' => ['privates', '.service_locator.pRI1W04', 'get_ServiceLocator_PRI1W04Service', true],
            'App\\Controller\\CadastroSocioController:excluir' => ['privates', '.service_locator.pRI1W04', 'get_ServiceLocator_PRI1W04Service', true],
            'App\\Controller\\CadastroSocioController:index' => ['privates', '.service_locator.Usrp9xw', 'get_ServiceLocator_Usrp9xwService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.8HRVZ6e', 'get_ServiceLocator_8HRVZ6eService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.V6D1oJY', 'get_ServiceLocator_V6D1oJYService', true],
            'App\\Controller\\VerEmpresaSociosController:index' => ['privates', '.service_locator.7zSLLSc', 'get_ServiceLocator_7zSLLScService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ApiGeradorPDFController::generatePdf' => '?',
            'App\\Controller\\CadastraEmpresaController::adicionar' => '?',
            'App\\Controller\\CadastraEmpresaController::editar' => '?',
            'App\\Controller\\CadastraEmpresaController::excluir' => '?',
            'App\\Controller\\CadastraEmpresaController::index' => '?',
            'App\\Controller\\CadastroSocioController::adicionar' => '?',
            'App\\Controller\\CadastroSocioController::editar' => '?',
            'App\\Controller\\CadastroSocioController::excluir' => '?',
            'App\\Controller\\CadastroSocioController::index' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\VerEmpresaSociosController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ApiGeradorPDFController:generatePdf' => '?',
            'App\\Controller\\CadastraEmpresaController:adicionar' => '?',
            'App\\Controller\\CadastraEmpresaController:editar' => '?',
            'App\\Controller\\CadastraEmpresaController:excluir' => '?',
            'App\\Controller\\CadastraEmpresaController:index' => '?',
            'App\\Controller\\CadastroSocioController:adicionar' => '?',
            'App\\Controller\\CadastroSocioController:editar' => '?',
            'App\\Controller\\CadastroSocioController:excluir' => '?',
            'App\\Controller\\CadastroSocioController:index' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\VerEmpresaSociosController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
